version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - '9200:9200'

  postgres:
    image: postgres:15
    container_name: postgres_real_estate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_estate_db
    ports:
      - '5433:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
